version: '3.8'

services:
  flask-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: host.docker.internal      # Host database di dalam jaringan Docker
      DB_USER: root     # Username untuk database
      DB_PASSWORD: ikh123
      DB_NAME: coba1
    restart: always

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ikh123
      MYSQL_DATABASE: coba1
    ports:
      - "3307:3306"
    restart: always

networks:
  default:
    driver: bridge
